# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название статьи')),
                ('text', models.TextField(default='', max_length=1300, verbose_name='Текст')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('author_name', models.CharField(default='Аноним', max_length=40, verbose_name='Имя автора')),
            ],
            options={
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
